name: Build Package

on:
  push:

jobs:
  build-msix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          Add-AppxProvisionedPackage -Path C:\offline -PackagePath C:\MSIX\MyPackage.msix -LicensePath C:\MSIX\MyLicense.xml

