name: Build Package

on:
  push:

jobs:
  build-msix:
    runs-on: windows-latest
    steps:    
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'saucelabs/saucectl'
          ref: 'v0.139.0'
          path: './saucectl/'

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build saucectl
        working-directory: ./saucectl/
        run: |
          mkdir C:\saucectl\

          $Env:GOOS="windows"
          $Env:GOARCH="amd64"
          go build -o ..\amd64\saucectl.exe cmd/saucectl/saucectl.go

          $Env:GOOS="windows"
          $Env:GOARCH="arm64"
          go build -o ..\arm64\saucectl.exe cmd/saucectl/saucectl.go

      - name: Build AppX (amd64)
        working-directory: ./amd64/
        run: |
          & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\MakeAppx.exe' pack /v /h SHA512 /p ..\saucectl_win-amd64.appx

      - name: Build AppX (arm64)
        working-directory: ./arm64/
        run: |
          & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\MakeAppx.exe' pack /v /h SHA512 /p ..\saucectl_win-arm64.appx

      - name: Sign AppX
        run: |
          & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool.exe' sign /fd SHA512 /a /f .\Certs.pfx /p ${{ secrets.PFX_PASSWORD }} .\saucectl_win-amd64.appx
          & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool.exe' sign /fd SHA512 /a /f .\Certs.pfx /p ${{ secrets.PFX_PASSWORD }} .\saucectl_win-arm64.appx

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: saucectl_win64.appx
          path: |
            saucectl_win-amd64.appx
            saucectl_win-arm64.appx
